#!/usr/bin/env ruby
# encod
require './lib/page_scraper'

class Fetch
  attr_reader :urls, :metadata

  def initialize(args)
    @metadata = !args.delete('--metadata').nil?
    @urls = args
  end

  def call
    if urls.empty?
      puts 'Usage: ./fetch url1 url2 [...]'
      exit(1)
    end

    PageScraper.new(urls, metadata).process
  end
end

Fetch.new(ARGV).call